Wireguard: don't enable CONFIG_ZINC_ARCH_ARM
bellow commit causes conflic
https://github.com/fgl27/BHB27Kernel/commit/de836e814f01dd0bcb029a9b286cb753461e30ac

b'/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h: Assembler messages:\n' None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `ret' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reteq' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retne' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retmi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retpl' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `rethi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retls' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retge' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retgt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retle' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reths' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlo' was already defined\n" None
make[3]: *** [/home/fgl27/android/quark/BHB27Kernel/scripts/Makefile.build:344: net/wireguard/crypto/zinc/chacha20/chacha20-unrolled-arm.o] Error 1
make[2]: *** [/home/fgl27/android/quark/BHB27Kernel/scripts/Makefile.build:455: net/wireguard] Error 2

b'/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h: Assembler messages:\n' None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `ret' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reteq' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retne' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retmi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retpl' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `rethi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retls' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retge' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retgt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retle' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reths' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlo' was already defined\n" None
make[3]: *** [/home/fgl27/android/quark/BHB27Kernel/scripts/Makefile.build:344: net/wireguard/crypto/zinc/curve25519/curve25519-arm.o] Error 1

b'/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h: Assembler messages:\n' None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `ret' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reteq' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retne' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retcc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retmi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retpl' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvs' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retvc' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `rethi' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retls' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retge' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retgt' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retle' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `reths' was already defined\n" None
b"/home/fgl27/android/quark/BHB27Kernel/arch/arm/include/asm/assembler.h:426: Error: Macro `retlo' was already defined\n" None
make[3]: *** [/home/fgl27/android/quark/BHB27Kernel/scripts/Makefile.build:344: net/wireguard/crypto/zinc/poly1305/poly1305-arm.o] Error 1

Signed-off-by: fgl27 <fglfgl27@gmail.com>