fs: Add TTY PM IOCTLs to compat table Augment the compat ioctl table with entries for PM control of TTY devices. These compat entries were not present since other TTY/serial core drivers were not using them.
Change-Id: I96a0e54c001d780a2a427380655f1fbb0091aef7
Signed-off-by: Naveen Kaje <nkaje@codeaurora.org>

fix

hardware/qcom/bt-caf/libbt-vendor/src/hci_uart.c:516:14: error: use of undeclared identifier 'TIOCPMGET'
        case USERIAL_OP_CLK_ON:
             ^
hardware/qcom/bt-caf/libbt-vendor/include/hci_uart.h:96:30: note: expanded from macro 'USERIAL_OP_CLK_ON'
                             ^
hardware/qcom/bt-caf/libbt-vendor/src/hci_uart.c:517:14: error: use of undeclared identifier 'TIOCPMPUT'
        case USERIAL_OP_CLK_OFF:
             ^
hardware/qcom/bt-caf/libbt-vendor/include/hci_uart.h:97:31: note: expanded from macro 'USERIAL_OP_CLK_OFF'
                              ^
hardware/qcom/bt-caf/libbt-vendor/src/hci_uart.c:520:14: error: use of undeclared identifier 'TIOCPMACT'
        case USERIAL_OP_CLK_STATE:
             ^
hardware/qcom/bt-caf/libbt-vendor/include/hci_uart.h:98:33: note: expanded from macro 'USERIAL_OP_CLK_STATE'

need this

https://github.com/CyanogenMod/android_hardware_qcom_bt/commit/d86185b093c5a0ca7b987d442b0dfdb882f16cc2